//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Core.Resources.CommonMessages", typeof(CommonMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإضافة بنجاح.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة {0} بنجاح.
        /// </summary>
        public static string AddSuccessFormat {
            get {
                return ResourceManager.GetString("AddSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملفات المسموحة هي:.
        /// </summary>
        public static string AllowedExtensions {
            get {
                return ResourceManager.GetString("AllowedExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عدد الملفات المسموحة هي:.
        /// </summary>
        public static string AllowedNoOfFiles {
            get {
                return ResourceManager.GetString("AllowedNoOfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} لا يقبل سوى أحرف عربية.
        /// </summary>
        public static string ArabicLettersOnlyErrorMessage {
            get {
                return ResourceManager.GetString("ArabicLettersOnlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التحقق.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإنشاء بنجاح.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء {0} بنجاح.
        /// </summary>
        public static string CreateSuccessFormat {
            get {
                return ResourceManager.GetString("CreateSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف {0} بنجاح.
        /// </summary>
        public static string DeleteSuccessFormat {
            get {
                return ResourceManager.GetString("DeleteSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح.
        /// </summary>
        public static string EditSuccess {
            get {
                return ResourceManager.GetString("EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل {0} بنجاح.
        /// </summary>
        public static string EditSuccessFormat {
            get {
                return ResourceManager.GetString("EditSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is No Data To Display.
        /// </summary>
        public static string Empty_Result_Message {
            get {
                return ResourceManager.GetString("Empty_Result_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} لا يقبل سوى أحرف إنجليزية.
        /// </summary>
        public static string EnglishLettersOnlyErrorMessage {
            get {
                return ResourceManager.GetString("EnglishLettersOnlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أبعاد الصورة غير صحيحة. الحد الأقصى للأبعاد المسموحة هي  {0}X{1}..
        /// </summary>
        public static string FileImageDimensionsErrorMessage {
            get {
                return ResourceManager.GetString("FileImageDimensionsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحقل {0} غير صحيح.
        /// </summary>
        public static string FileInValidErrorMessage {
            get {
                return ResourceManager.GetString("FileInValidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف المرفق ليس صورة صحيحة. برجاء إرفاق ملف صورة.
        /// </summary>
        public static string FileNotValidImageErrorMessage {
            get {
                return ResourceManager.GetString("FileNotValidImageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملفات.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الملف غير مسموح. الحد الأقصى لحجم الملف هو {0} ميجا بايت.
        /// </summary>
        public static string FileSizeErrorMessage {
            get {
                return ResourceManager.GetString("FileSizeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ملف غير صحيح. برجاء إرفاق ملف من نوع {0} فقط.
        /// </summary>
        public static string FileTypeErrorMessage {
            get {
                return ResourceManager.GetString("FileTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف فارغ.
        /// </summary>
        public static string FileZeroLengthErrorMessage {
            get {
                return ResourceManager.GetString("FileZeroLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Model Attributes.
        /// </summary>
        public static string FormatPartialTagHelper_InvalidModelAttributes {
            get {
                return ResourceManager.GetString("FormatPartialTagHelper_InvalidModelAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallback View Not Found.
        /// </summary>
        public static string FormatViewEngine_FallbackViewNotFound {
            get {
                return ResourceManager.GetString("FormatViewEngine_FallbackViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial View Not Found.
        /// </summary>
        public static string FormatViewEngine_PartialViewNotFound {
            get {
                return ResourceManager.GetString("FormatViewEngine_PartialViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميلادي.
        /// </summary>
        public static string Gregorian {
            get {
                return ResourceManager.GetString("Gregorian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صيغة التاريخ غير صحيحة.
        /// </summary>
        public static string InvalidDateTime {
            get {
                return ResourceManager.GetString("InvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحداثيات الموقع الجغرافي غير صحيحة.
        /// </summary>
        public static string LocationLatLonErrorMessage {
            get {
                return ResourceManager.GetString("LocationLatLonErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى لحجم الملف هو.
        /// </summary>
        public static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى لإرتفاع الصورة هو.
        /// </summary>
        public static string MaxImageHeight {
            get {
                return ResourceManager.GetString("MaxImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى لعرض الصورة هو.
        /// </summary>
        public static string MaxImageWidth {
            get {
                return ResourceManager.GetString("MaxImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميجا بايت.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب الموافقة على الشروط والاحكام.
        /// </summary>
        public static string MustAcceptAgreement {
            get {
                return ResourceManager.GetString("MustAcceptAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون قيمة الحقل مختارة.
        /// </summary>
        public static string MustBeTrueError {
            get {
                return ResourceManager.GetString("MustBeTrueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم موجود مسبقا.
        /// </summary>
        public static string NoDublicateDate {
            get {
                return ResourceManager.GetString("NoDublicateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحد الأقصى للملفات المسموحة هو {0}.
        /// </summary>
        public static string NoOfFilesErrorMessage {
            get {
                return ResourceManager.GetString("NoOfFilesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} يسمح فقط بالأرقام.
        /// </summary>
        public static string NumberOnlyErrorMessage {
            get {
                return ResourceManager.GetString("NumberOnlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معالجة الملفات ....
        /// </summary>
        public static string ProcessingDroppedFiles {
            get {
                return ResourceManager.GetString("ProcessingDroppedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ {0} بنجاح.
        /// </summary>
        public static string SaveSuccessFormat {
            get {
                return ResourceManager.GetString("SaveSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يسمح بكتابة سكريبت في هذا الحقل.
        /// </summary>
        public static string ScriptsNotAllowedErrorMessage {
            get {
                return ResourceManager.GetString("ScriptsNotAllowedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الملفات.
        /// </summary>
        public static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجري.
        /// </summary>
        public static string UmmAlqura {
            get {
                return ResourceManager.GetString("UmmAlqura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في حال لم تقم بإرفاق ملف سيتم المحافظة على الملف القديم.
        /// </summary>
        public static string UploaderOptionalInEditMode {
            get {
                return ResourceManager.GetString("UploaderOptionalInEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} يسمح فقط برقم سنة صحيح.
        /// </summary>
        public static string YearOnlyErrorMessage {
            get {
                return ResourceManager.GetString("YearOnlyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
