// <auto-generated />
using System;
using Framework.Notifications.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Framework.Notifications.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    [Migration("20230316111754_Notifications_FixTemplatesLayoutLogo")]
    partial class Notifications_FixTemplatesLayoutLogo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Framework.Notifications.Entities.NotificationQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttachmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SendErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("SendStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationQueue", "Notifications");
                });

            modelBuilder.Entity("Framework.Notifications.Entities.NotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationSetting", "Notifications");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "DisableSMSNotifications",
                            NameEn = "DisableSMSNotifications",
                            Value = "FALSE"
                        },
                        new
                        {
                            Id = 20,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "DisableEmailNotifications",
                            NameEn = "DisableEmailNotifications",
                            Value = "FALSE"
                        },
                        new
                        {
                            Id = 30,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "EmailSubjectAr",
                            NameEn = "EmailSubjectAr",
                            Value = "Tasjeel Tech"
                        },
                        new
                        {
                            Id = 40,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "SmtpServer",
                            NameEn = "SmtpServer",
                            Value = "exch-array.citc.gov.sa"
                        },
                        new
                        {
                            Id = 50,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "SmtpUserName",
                            NameEn = "SmtpUserName",
                            Value = "Tasjeeltech@citc.gov.sa"
                        },
                        new
                        {
                            Id = 60,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "SmtpPassword",
                            NameEn = "SmtpPassword",
                            Value = "AzswQ@123753@zizadqhhdone"
                        },
                        new
                        {
                            Id = 70,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "IsSmtpAuthenticated",
                            NameEn = "IsSmtpAuthenticated",
                            Value = "TRUE"
                        },
                        new
                        {
                            Id = 80,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "SmtpPort",
                            NameEn = "SmtpPort",
                            Value = "587"
                        },
                        new
                        {
                            Id = 90,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "SmtpEnableSSL",
                            NameEn = "SmtpEnableSSL",
                            Value = "FALSE"
                        },
                        new
                        {
                            Id = 100,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "EmailFromAddress",
                            NameEn = "EmailFromAddress",
                            Value = "Tasjeeltech@citc.gov.sa"
                        },
                        new
                        {
                            Id = 110,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "EmailFromName",
                            NameEn = "EmailFromName",
                            Value = "Tasjeel Tech"
                        },
                        new
                        {
                            Id = 120,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "ContactUsEmail",
                            NameEn = "ContactUsEmail",
                            Value = "Tasjeeltech@citc.gov.sa"
                        },
                        new
                        {
                            Id = 130,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "EmailSubject",
                            NameEn = "EmailSubject",
                            Value = "Tasjeel Tech"
                        },
                        new
                        {
                            Id = 140,
                            ApplicationId = "",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            IsDeleted = false,
                            Key = "ApplicationUrl",
                            NameEn = "ApplicationUrl",
                            Value = "http://localhost:44309/"
                        });
                });

            modelBuilder.Entity("Framework.Notifications.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTML")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HTMLAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectAr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("NotificationTemplate", "Notifications");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<html xmlns=\"http://www.w3.org/1999/xhtml\" dir=\"rtl\"><head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n    <title style=\"dispaly:none\">CST</title>\r\n</head>\r\n<body dir=\"ltr\" style=\"padding:0px\">\r\n  <div style=\"background-color: #040063;text-align:center;width:100%;\">\r\n<img src=\"{RootUrl}/CITC/images/Logo.png\" min-width=\"30%\" class=\"email_header\" style=\"border:1px solid #ddd;max-width:30%\">\r\n</div>\r\n    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n        <tbody><tr>\r\n            <td class=\"email_conts\" style=\"padding:10px 20px;  font:11px Segoe UI,tahoma;  line-height:20px;  color:#404040;  text-align:right;  border:1px solid #eee;  border-top:none\">\r\n                <div dir=\"ltr\">\r\n				{body}\r\n</div>\r\n<div dir=\"rtl\">\r\n{bodyAr}\r\n</div>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td class=\"email_footer\" width=\"600\" style=\"padding:10px 0;  background-color:#030062;  color:#fff;  font:11px Segoe UI,tahoma;  text-align:center\">\r\n                For your suggestions and comments, send us an e-mail: <a href=\"{ContactUsEmail}\" style=\"color:#fff;  font:11px Segoe UI,tahoma\">{ContactUsEmail}</a>\r\n            </td>\r\n        </tr>\r\n    </tbody></table>\r\n\r\n</body></html>",
                            HTMLAr = "<html xmlns=\"http://www.w3.org/1999/xhtml\" dir=\"rtl\"><head>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n    <title style=\"dispaly:none\">CST</title>\r\n</head>\r\n<body dir=\"ltr\" style=\"padding:0px\">\r\n  <div style=\"background-color: #040063;text-align:center;width:100%;\">\r\n<img src=\"{RootUrl}/CITC/images/Logo.png\" min-width=\"30%\" class=\"email_header\" style=\"border:1px solid #ddd;max-width:30%\">\r\n</div>\r\n    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n        <tbody><tr>\r\n            <td class=\"email_conts\" style=\"padding:10px 20px;  font:11px Segoe UI,tahoma;  line-height:20px;  color:#404040;  text-align:right;  border:1px solid #eee;  border-top:none\">\r\n                <div dir=\"ltr\">\r\n				{body}\r\n</div>\r\n<div dir=\"rtl\">\r\n{bodyAr}\r\n</div>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td class=\"email_footer\" width=\"600\" style=\"padding:10px 0;  background-color:#030062;  color:#fff;  font:11px Segoe UI,tahoma;  text-align:center\">\r\n                For your suggestions and comments, send us an e-mail: <a href=\"{ContactUsEmail}\" style=\"color:#fff;  font:11px Segoe UI,tahoma\">{ContactUsEmail}</a>\r\n            </td>\r\n        </tr>\r\n    </tbody></table>\r\n\r\n</body></html>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "EmailLayoutTemplate",
                            NameEn = "EmailLayoutTemplate",
                            NotificationTypeId = 100,
                            Subject = "EmailLayoutTemplate",
                            SubjectAr = "EmailLayoutTemplate"
                        },
                        new
                        {
                            Id = 1401,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">Dear {UserFullNameEn}</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">Greetings,\r\n<p style=\"text-align: left;\">Your request has been successfully submitted , and it will be studied and answered within 15 days</p>\r\n</h3>",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">المكرم {UserFullNameAr}</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n<p>تمت إرسال طلبك بنجاح وستتم دراسته والرد عليكم خلال 15 يومًا من تاريخ تقديم الطلب.</p> \r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Submitter_RequestSubmittedSucessfully",
                            NameEn = "Submitter_RequestSubmittedSucessfully",
                            NotificationTypeId = 100,
                            Subject = "Your request has been submitted",
                            SubjectAr = "تم إرسال طلبك بنجاح"
                        },
                        new
                        {
                            Id = 1402,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}\r\n\r\nGreetings,\r\n\r\nYour request has been successfully submitted , and it will be studied and answered within 15 days",
                            HTMLAr = "المكرم {UserFullNameAr}\r\n\r\nتحية طيبة،\r\n\r\nتمت إرسال طلبك بنجاح وستتم دراسته والرد عليكم خلال 15 يومًا من تاريخ تقديم الطلب.",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Submitter_RequestSubmittedSucessfully",
                            NameEn = "Submitter_RequestSubmittedSucessfully",
                            NotificationTypeId = 200,
                            Subject = "Your request has been submitted",
                            SubjectAr = "تم إرسال طلبك بنجاح"
                        },
                        new
                        {
                            Id = 1501,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">Dear {UserFullNameEn}</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">Greetings,\r\n<p style=\"text-align: left;\">Kindly log in to Manassa Tech platform to study the request to attend a session added to your assignment box via the following link: {InternalUrl}</p><h3>",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">المكرم {UserFullNameAr} المشرف</h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n    <p>نأمل منكم التكرم بزيارة منصة تك لدراسة طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}</p> \r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Supervisor_RequestSubmittedWaitingForReview",
                            NameEn = "Supervisor_RequestSubmittedWaitingForReview",
                            NotificationTypeId = 100,
                            Subject = "A request has been submitted for review",
                            SubjectAr = "تم إرسال طلب للمراجعة"
                        },
                        new
                        {
                            Id = 1502,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}\r\n\r\nGreetings,\r\n\r\nKindly log in to Manassa Tech platform to study the request to attend a session added to your assignment box via the following link: {InternalUrl}",
                            HTMLAr = "المكرم {UserFullNameAr} المشرف \r\n\r\nتحية طيبة،\r\n\r\nنأمل منكم التكرم بزيارة منصة تك لدراسة طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Supervisor_RequestSubmittedWaitingForReview",
                            NameEn = "Supervisor_RequestSubmittedWaitingForReview",
                            NotificationTypeId = 200,
                            Subject = "A request has been submitted for review",
                            SubjectAr = "تم إرسال طلب للمراجعة"
                        },
                        new
                        {
                            Id = 1601,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">Dear {UserFullNameEn}</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">Greetings,\r\n    <p style=\"text-align: left;\">Kindly log in to Manassa Tech platform to study the request to attend a session added to your assignment box via the following link: {InternalUrl}</p>\r\n</h3>",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">المكرم {UserFullNameAr} المشرف</h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n    <p>نأمل منكم التكرم بزيارة منصة تك  لدراسة طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}</p> \r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Reviewer_AssignedOnRequestToReview",
                            NameEn = "Reviewer_AssignedOnRequestToReview",
                            NotificationTypeId = 100,
                            Subject = "You have a new request to study",
                            SubjectAr = "طلب جديد للدراسة"
                        },
                        new
                        {
                            Id = 1602,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}\r\n\r\nGreetings,\r\n\r\nKindly log in to Manassa Tech platform to study the request added to your assignment box via the following link: {InternalUrl}",
                            HTMLAr = "المكرم {UserFullNameAr}\r\n\r\nتحية طيبة،\r\n\r\nنأمل منكم التكرم بزيارة منصة تك لدراسة طلب {RequestTypeAr} شركة المضاف لصندوق المهام الخاص بكم عبر الرابط التالي:{InternalUrl}",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Reviewer_AssignedOnRequestToReview",
                            NameEn = "Reviewer_AssignedOnRequestToReview",
                            NotificationTypeId = 200,
                            Subject = "You have a new request to study",
                            SubjectAr = "طلب جديد للدراسة"
                        },
                        new
                        {
                            Id = 1701,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">Dear {UserFullNameEn}</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">Greetings,\r\n    <p style=\"text-align: left;\">Kindly log in to the company registration platform to study the request to examine financial information added to your assignment box via the following link: {InternalUrl}\r\n    </p>\r\n</h3>",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">المكرم {UserFullNameAr} المشرف</h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n    <p>نأمل منكم التكرم بزيارة منصة تك لدراسة المعلومات المالية المضافة لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}</p> \r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Supervisor_ReviewerApprovedTheRequest",
                            NameEn = "Supervisor_ReviewerApprovedTheRequest",
                            NotificationTypeId = 100,
                            Subject = "A request has been submitted for review",
                            SubjectAr = "تم إرسال طلب للمراجعة"
                        },
                        new
                        {
                            Id = 1702,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}\r\n\r\nGreetings,\r\n\r\nKindly log in to the company registration platform to study the request to examine financial information added to your assignment box via the following link: {InternalUrl}",
                            HTMLAr = "المكرم {UserFullNameAr} المشرف\r\n\r\nتحية طيبة،\r\n\r\nنأمل منكم التكرم بزيارة منصة تك لدراسة المعلومات المالية المضافة لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Supervisor_ReviewerApprovedTheRequest",
                            NameEn = "Supervisor_ReviewerApprovedTheRequest",
                            NotificationTypeId = 200,
                            Subject = "A request has been submitted for review",
                            SubjectAr = "تم إرسال طلب للمراجعة"
                        },
                        new
                        {
                            Id = 1801,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">Dear {UserFullNameEn} Director of the Department</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">Greetings,\r\n    <p style=\"text-align: left;\">Kindly log in to the company registration platform to approve the request to approve the {RequestType} request added to your assignment box via the following link: {InternalUrl}</p>\r\n</h3>",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">المكرم {UserFullNameAr} مدير الإدارة</h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n    <p >نأمل منكم التكرم &nbsp;بزيارة منصة تك لاعتماد طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}</p> \r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Director_HasNewRequestToReview",
                            NameEn = "Director_HasNewRequestToReview",
                            NotificationTypeId = 100,
                            Subject = "A request has been submitted for approval",
                            SubjectAr = "إرسال طلب للاعتماد"
                        },
                        new
                        {
                            Id = 1802,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn} Director of the Department\r\n\r\nGreetings,\r\n\r\nKindly log in to Manassa Tech platform to approve the request to approve the {RequestType} request added to your assignment box via the following link: {InternalUrl}",
                            HTMLAr = "المكرم {UserFullNameAr} مدير الإدارة\r\n\r\nتحية طيبة،\r\n\r\nنأمل منكم التكرم  بزيارة منصة تك لاعتماد طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Director_HasNewRequestToReview",
                            NameEn = "Director_HasNewRequestToReview",
                            NotificationTypeId = 200,
                            Subject = "A request has been submitted for approval",
                            SubjectAr = "إرسال طلب للاعتماد"
                        },
                        new
                        {
                            Id = 1901,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">Dear {UserFullNameEn}, the authorized person for the company {CompanyName}</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">Greetings,\r\n    <p style=\"text-align: left;\">Kindly log in to Manassa Tech platform to amend the notes received from the reviewers on your registration at CITC via the following link: {ExternalUrl}</p>\r\n</h3>",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n    <p>نأمل منكم التكرم بزيارة منصة تك لتعديل الملاحظات الواردة على الطلب تسجيلكم في الهيئة عبر الرابط التالي: {ExternalUrl}</p> \r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Submitter_RequestNeedsMoreInfo",
                            NameEn = "Submitter_RequestNeedsMoreInfo",
                            NotificationTypeId = 100,
                            Subject = "Please review the registration request for some notes.",
                            SubjectAr = "حالة طلب التسجيل"
                        },
                        new
                        {
                            Id = 1902,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\n\r\nGreetings,\r\n\r\nKindly log in to Manassa Tech platform to amend the notes received from the reviewers on your {RequestType} at CITC via the following link: {ExternalUrl}",
                            HTMLAr = "المكرم {UserFullNameAr} المفوض لشركة {CompanyName}\r\n\r\nتحية طيبة،\r\n\r\nنأمل منكم التكرم بزيارة منصة تك لتعديل الملاحظات الواردة على الطلب {RequestTypeAr} في الهيئة عبر الرابط التالي: {ExternalUrl}",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Submitter_RequestNeedsMoreInfo",
                            NameEn = "Submitter_RequestNeedsMoreInfo",
                            NotificationTypeId = 200,
                            Subject = "Please review the registration request for some notes.",
                            SubjectAr = "حالة طلب التسجيل"
                        },
                        new
                        {
                            Id = 2001,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">Dear {UserFullNameEn}, the authorized person for the company {CompanyName}</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">Greetings,\r\n    <p style=\"text-align: left;\">We regret to inform you that your {RequestType} request with CITC is rejected , You can review your request via the following link: {ExternalUrl}</p>\r\n</h3>",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n    <p>نأسف لإبلاغكم برفض طلب {RequestTypeAr} في منصة تك بهيئة الاتصالات وتقنية المعلومات. للاطلاع على تفاصيل الرفض والملاحظات:{ExternalUrl}.</p> \r\n\r\n\r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Submitter_RequestRejected",
                            NameEn = "Submitter_RequestRejected",
                            NotificationTypeId = 100,
                            Subject = "Request status",
                            SubjectAr = "حالة طلب التسجيل"
                        },
                        new
                        {
                            Id = 2002,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\n\r\nGreetings,\r\n\r\nWe regret to inform you that your {RequestType} request with CITC is rejected for these reasons: {Reason} , You can review your request via the following link: {ExternalUrl}",
                            HTMLAr = "المكرم {UserFullNameAr} المفوض لشركة {CompanyName}\r\n\r\nتحية طيبة،\r\n\r\nنأسف لإبلاغكم برفض طلب {RequestTypeAr} في منصة تك بهيئة الاتصالات وتقنية المعلومات. للاطلاع على تفاصيل الرفض والملاحظات:{ExternalUrl}.\r\n",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Submitter_RequestRejected",
                            NameEn = "Submitter_RequestRejected",
                            NotificationTypeId = 200,
                            Subject = "Request status",
                            SubjectAr = "حالة طلب التسجيل"
                        },
                        new
                        {
                            Id = 2051,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">Dear {UserFullNameEn}, the authorized person for the company {CompanyName}</h2>\r\n<h3 style=\"text-align:justify;font-weight:normal;\">Greetings,\r\n    <p style=\"text-align: left;\">We are pleased to inform you that your {RequestType} request with CITC is approved  , You can review your request via the following link: {ExternalUrl}</p>\r\n</h3>",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n    <p>نسعد لإبلاغكم بقبول طلب {RequestTypeAr} في منصة تك بهيئة الاتصالات وتقنية المعلومات. للاطلاع على تفاصيل الطلب والملاحظات:{ExternalUrl}.</p> \r\n \r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Submitter_RequestApproved",
                            NameEn = "Submitter_RequestApproved",
                            NotificationTypeId = 100,
                            Subject = "Request status",
                            SubjectAr = "حالة طلب التسجيل"
                        },
                        new
                        {
                            Id = 2052,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\n\r\nGreetings,\r\n\r\nWe are please to inform you that your {RequestType} request with CITC is approved , You can review your request via the following link: {ExternalUrl}",
                            HTMLAr = "المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}\r\n\r\nتحية طيبة،\r\n\r\nيسعدنا لإبلاغكم بقبول طلب {RequestTypeAr} في منصة تك بهيئة الاتصالات وتقنية المعلومات. للاطلاع على تفاصيل الطلب والملاحظات:{ExternalUrl}.\r\n\r\n ",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Submitter_RequestApproved",
                            NameEn = "Submitter_RequestApproved",
                            NotificationTypeId = 200,
                            Subject = "Request status",
                            SubjectAr = "حالة طلب التسجيل"
                        },
                        new
                        {
                            Id = 2201,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\" > Dear {UserFullNameEn}, the authorized person for the company {CompanyName} </h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\" >Greetings،\r\n    <p>Kindly be informed that the company profile will be suspended due to the near expiration of the commercial registery.\r\nSo please make sure that the commercial registery renewed and login to the portal to update this information.\r\n</p> \r\n            </h3>\"",
                            HTMLAr = "<h2 style=\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\">  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"text-align:justify;font-weight:normal;\">تحية طيبة،\r\n    <p>يرجى العلم أنه سيتم تعليق الملف التعريفي للشركة بسبب قرب انتهاء صلاحية السجل التجاري.\r\nلذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لتحديث هذه المعلومات.</p> \r\n            </h3>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "CRPreExpirationNotification",
                            NameEn = "CRPreExpirationNotification",
                            NotificationTypeId = 100,
                            Subject = "CR pre expiration notification alert",
                            SubjectAr = "إشعار بقرب انتهاء السجل التجاري"
                        },
                        new
                        {
                            Id = 2202,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\nGreetings,\r\nKindly be informed that the company profile will be suspended due to the near expiration of the commercial registery.\r\nSo please make sure that the commercial registery renewed and login to the portal to update this information.\"",
                            HTMLAr = "\"المكرم {UserFullNameAr} المفوض لشركة {CompanyName}\r\nتحية طيبة،\r\nيرجى العلم أنه سيتم تعليق الملف التعريفي للشركة بسبب قرب انتهاء صلاحية السجل التجاري.\r\nلذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لتحديث هذه المعلومات.\r\n \"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "CRPreExpirationNotification",
                            NameEn = "CRPreExpirationNotification",
                            NotificationTypeId = 200,
                            Subject = "CR pre expiration notification alert",
                            SubjectAr = "إشعار بقرب انتهاء السجل التجاري"
                        },
                        new
                        {
                            Id = 2211,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\"> Dear {UserFullNameEn}, the authorized person for the company {CompanyName} </h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\"> Greetings.  ،\r\n    <p>\r\nKindly be informed that tomorrow the company profile will be suspended due to the  expiration of the commercial registery.\r\nSo please make sure that the commercial registery renewed and login to the portal to update this information.</p> \r\n            </h3>\"",
                            HTMLAr = "\"\r\n<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\">  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\">تحية طيبة،\r\n <p>\r\nيرجى العلم أنه غدا سيتم تعليق الملف التعريفي للشركة بسبب انتهاء صلاحية السجل التجاري اليوم.\r\nلذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لتحديث هذه المعلومات.\r\n</p> \r\n            </h3>\"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "CRExpiringNotification",
                            NameEn = "CRExpiringNotification",
                            NotificationTypeId = 100,
                            Subject = "CR expiring notification alert",
                            SubjectAr = "إشعار بانتهاء السحل التجاري اليوم"
                        },
                        new
                        {
                            Id = 2212,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\nGreetings,\r\nKindly be informed that tomorrow the company profile will be suspended due to the  expiration of the commercial registery.\r\nSo please make sure that the commercial registery renewed and login to the portal to update this information.\"",
                            HTMLAr = "\"المكرم {UserFullNameAr} المفوض لشركة {CompanyName}\r\nتحية طيبة،\r\nيرجى العلم أنه غدا سيتم تعليق الملف التعريفي للشركة بسبب انتهاء صلاحية السجل التجاري اليوم.\r\nلذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لتحديث هذه المعلومات. \"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "CRExpiringNotification",
                            NameEn = "CRExpiringNotification",
                            NotificationTypeId = 200,
                            Subject = "CR expiring notification alert",
                            SubjectAr = "إشعار بانتهاء السحل التجاري اليوم"
                        },
                        new
                        {
                            Id = 2221,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\"> Dear {UserFullNameEn}, the authorized person for the company {CompanyName} </h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\"> Greetings.  ،\r\n    <p>\r\nKindly be informed that  the company profile has been suspended due to the  expiration of the commercial registery.\r\nSo please make sure that the commercial registery renewed and login to the portal to reactivate the profile again.</p> \r\n            </h3>\"",
                            HTMLAr = "\"\r\n<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\">  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\">تحية طيبة،\r\n <p>\r\nيرجى العلم أنه تم  تعليق الملف التعريفي للشركة بسبب   انتهاء صلاحية السجل التجاري.\r\nلذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لإعادة تفعيل ملف الشركة.\r\n</p> \r\n            </h3>\"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "CRExpiredNotification",
                            NameEn = "CRExpiredNotification",
                            NotificationTypeId = 100,
                            Subject = "CR expired notification alert",
                            SubjectAr = "إشعار بانتهاء السجل التجاري"
                        },
                        new
                        {
                            Id = 2222,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\nGreetings,\r\nKindly be informed that  the company profile has been suspended due to the  expiration of the commercial registery.\r\nSo please make sure that the commercial registery renewed and login to the portal to reactivate the profile again.",
                            HTMLAr = "\"المكرم {UserFullNameAr} المفوض لشركة {CompanyName}\r\nتحية طيبة،\r\n  يرجى العلم أنه تم  تعليق الملف التعريفي للشركة بسبب   انتهاء صلاحية السجل التجاري.\r\nلذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لإعادة تفعيل ملف الشركة\"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "CRExpiredNotification",
                            NameEn = "CRExpiredNotification",
                            NotificationTypeId = 200,
                            Subject = "CR expired notification alert",
                            SubjectAr = "إشعار بانتهاء السجل التجاري"
                        },
                        new
                        {
                            Id = 2231,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\">  Dear {UserFullNameEn}, the authorized person for the company {CompanyName}</h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\">Greetings,\r\n <p>\r\n Kindly be informed that the company profile will be expired after one month.\r\nSo please login to the portal to apply profile renew request\r\n</p> \r\n            </h3>",
                            HTMLAr = "\"\r\n<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\">  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\">تحية طيبة،\r\n <p>\r\nيرجى العلم أنه باقى شهر على انتهاء صلاحية ملف الشركة .\r\nلذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة.\r\n</p> \r\n            </h3>\"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ProfilePreExpirationNotification",
                            NameEn = "ProfilePreExpirationNotification",
                            NotificationTypeId = 100,
                            Subject = "Profile pre expiration notification alert",
                            SubjectAr = "إشعار بقرب انتهاء صلاحية التسجيل"
                        },
                        new
                        {
                            Id = 2232,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\nGreetings,\r\nKindly be informed that  the company profile will be expired after one month.\r\nSo please login to the portal to apply profile renew request.\"",
                            HTMLAr = "\"المكرم {UserFullNameAr} المفوض لشركة {CompanyName}\r\nتحية طيبة،\r\nيرجى العلم أنه باقى شهر على انتهاء صلاحية ملف الشركة .\r\nلذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة. \r\n \"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ProfilePreExpirationNotification",
                            NameEn = "ProfilePreExpirationNotification",
                            NotificationTypeId = 200,
                            Subject = "Profile pre expiration notification alert",
                            SubjectAr = "إشعار بقرب انتهاء صلاحية التسجيل"
                        },
                        new
                        {
                            Id = 2241,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\"> Dear {UserFullNameEn}, the authorized person for the company {CompanyName} </h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\"> Greetings. \r\n    <p>\r\nKindly be informed that tommorrow the company profile will be expired.\r\nSo please login to the portal to apply profile renew request.\r\n</p> \r\n            </h3>\"",
                            HTMLAr = "\"\r\n<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\">  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\">تحية طيبة،\r\n <p>\r\nيرجى العلم أنه باقى يوم على انتهاء صلاحية ملف الشركة .\r\nلذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة.\r\n</p> \r\n            </h3>\"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ProfileExpiringNotification",
                            NameEn = "ProfileExpiringNotification",
                            NotificationTypeId = 100,
                            Subject = "Profile expiring notification alert",
                            SubjectAr = "إشعار بانتهاء صلاحية التسجيل اليوم"
                        },
                        new
                        {
                            Id = 2242,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\nGreetings,\r\nKindly be informed that tommorrow the company profile will be expired.\r\nSo please login to the portal to apply profile renew request.\"",
                            HTMLAr = "\"المكرم {UserFullNameAr} المفوض لشركة {CompanyName}\r\nتحية طيبة،\r\nيرجى العلم أنه باقى يوم على انتهاء صلاحية ملف الشركة .\r\nلذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة. \"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ProfileExpiringNotification",
                            NameEn = "ProfileExpiringNotification",
                            NotificationTypeId = 200,
                            Subject = "Profile expiring notification alert",
                            SubjectAr = "إشعار بانتهاء صلاحية التسجيل اليوم"
                        },
                        new
                        {
                            Id = 2251,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\"> Dear {UserFullNameEn}, the authorized person for the company {CompanyName} </h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\"> Greetings. \r\n    <p>\r\nKindly be informed that  the company profile has been suspended due to the  expiration of the registration.\r\nSo please login to the portal to apply profile renew request.</p> \r\n            </h3>\"",
                            HTMLAr = "\"\r\n<h2 style=\"\"color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;\"\">  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}</h2>\r\n            <h3 style=\"\"text-align:justify;font-weight:normal;\"\">تحية طيبة،\r\n <p>\r\nيرجى العلم أنه تم  تعليق الملف التعريفي للشركة بسبب انتهاء صلاحية التسجيل.\r\nلذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة.\r\n</p> \r\n            </h3>\"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ProfileExpiredNotification",
                            NameEn = "ProfileExpiredNotification",
                            NotificationTypeId = 100,
                            Subject = "Profile expired notification alert",
                            SubjectAr = "إشعار بالنتهاء صلاحية التسجيل"
                        },
                        new
                        {
                            Id = 2252,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "\"Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\nGreetings,\r\nKindly be informed that  the company profile has been suspended due to the  expiration of the registration.\r\nSo please login to the portal to apply profile renew request.\"",
                            HTMLAr = "\"Dear {UserFullNameEn}, the authorized person for the company {CompanyName}\r\nGreetings,\r\nKindly be informed that  the company profile has been suspended due to the  expiration of the registration.\r\nSo please login to the portal to apply profile renew request.\"",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "ProfileExpiredNotification",
                            NameEn = "ProfileExpiredNotification",
                            NotificationTypeId = 200,
                            Subject = "Profile expired notification alert",
                            SubjectAr = "إشعار بالنتهاء صلاحية التسجيل"
                        },
                        new
                        {
                            Id = 2401,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<h2 style=\"color: #030062; font-size: 15px; line-height: 25px; text-align: justify; font-weight: bold;\">Dear {NameEn}</h2>\r\n<h3 style=\"text-align: justify; font-weight: normal;\">Greetings,</h3>\r\n<p style=\"text-align: left;\">Kindly use the following code to activate your email {Code} so you can keep procced</p>",
                            HTMLAr = "<h2 style=\"color: #030062; font-size: 15px; line-height: 25px; text-align: justify; font-weight: bold;\">المكرم {NameAr} \r\n<h3 style=\"text-align: justify; font-weight: normal;\">تحية طيبة،</h3>\r\n<p>.الرجاء إستخدام الرمز التالي لتفعيل البريد الإلكتروني {Code} </p>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "EmailCodeVerification",
                            NameEn = "EmailCodeVerification",
                            NotificationTypeId = 100,
                            Subject = "Email confirmation",
                            SubjectAr = "توثيق البريد الإلكتروني"
                        },
                        new
                        {
                            Id = 2502,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Kindly use the following code to activate your phone number: {Code} ",
                            HTMLAr = " نأمل استخدام الرمز التالي لتفعيل رقم الهاتف: {Code}\r\n  ",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "NumberCodeVerification",
                            NameEn = "NumberCodeVerification",
                            NotificationTypeId = 200,
                            Subject = "Mobile confirmation",
                            SubjectAr = "توثيق رقم الهاتف"
                        },
                        new
                        {
                            Id = 3001,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<p>Dear {UserFullNameEn}</p>\r\n<p>Greetings,</p>\r\n<p>Please note that there are late request with number ({RequestNumber}) that no action has been taken on them yet .... Kindly take the necessary action ..</p>",
                            HTMLAr = "<p style=\"direction: rtl;\">المكرم {UserFullNameEn}</p>\r\n<p style=\"direction: rtl;\">تحية طيبة،</p>\r\n<p style=\"direction: rtl;\">نفيدكم بوجود طلب متأخر برقم {RequestNumber} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ..</p>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "EscalationTemplate",
                            NameEn = "EscalationTemplate",
                            NotificationTypeId = 100,
                            Subject = "Request escalated",
                            SubjectAr = "تم تصعيد الطلب"
                        },
                        new
                        {
                            Id = 3002,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}\r\nGreetings,\r\nPlease note that there are late request with number ({RequestNumber}) that no action has been taken on them yet .... Kindly take the necessary action ..",
                            HTMLAr = "السيد المكرم {UserFullNameEn}\r\n\r\nتحية طيبة،\r\n\r\nنفيدكم بوجود طلب متأخر برقم {RequestNumber} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ..",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "EscalationTemplate",
                            NameEn = "EscalationTemplate",
                            NotificationTypeId = 200,
                            Subject = "Request escalated",
                            SubjectAr = "تم تصعيد الطلب"
                        },
                        new
                        {
                            Id = 3101,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "<p>Dear {UserFullNameEn}</p>\r\n<p>Greetings,</p>\r\n<p>Please note that there are late request with number ({RequestNumber}) that no action has been taken on them yet .... Kindly take the necessary action ..</p>",
                            HTMLAr = "<p style=\"direction: rtl;\">المكرم {UserFullNameEn}</p>\r\n<p style=\"direction: rtl;\">تحية طيبة،</p>\r\n<p style=\"direction: rtl;\">نفيدكم بوجود طلب متأخر برقم {RequestNumber} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ..</p>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "EscalationReminderTemplate",
                            NameEn = "EscalationReminderTemplate",
                            NotificationTypeId = 100,
                            Subject = "Reminder to take action on the task",
                            SubjectAr = "التذكير باتخاذ اجراء على المهمة"
                        },
                        new
                        {
                            Id = 3102,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullNameEn}\r\nGreetings,\r\nPlease note that there are late request with number ({RequestNumber}) that no action has been taken on them yet .... Kindly take the necessary action ..",
                            HTMLAr = "السيد المكرم {UserFullNameEn}\r\n\r\nتحية طيبة،\r\n\r\nنفيدكم بوجود طلب متأخر برقم {RequestNumber} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ..",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "EscalationReminderTemplate",
                            NameEn = "EscalationReminderTemplate",
                            NotificationTypeId = 200,
                            Subject = "Reminder to take action on the task",
                            SubjectAr = "التذكير باتخاذ اجراء على المهمة"
                        },
                        new
                        {
                            Id = 4001,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HTML = "Dear {UserFullName} / Company {CompanyName}\r\n\r\n{Body}",
                            HTMLAr = "<span></span>",
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "CompaniesMessageNotification",
                            NameEn = "CompaniesMessageNotification",
                            NotificationTypeId = 100,
                            Subject = "Companies messages notification",
                            SubjectAr = "رسائل الشركات"
                        });
                });

            modelBuilder.Entity("Framework.Notifications.Entities.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationType", "Notifications");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Email",
                            NameEn = "Email"
                        },
                        new
                        {
                            Id = 200,
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "Sms",
                            NameEn = "Sms"
                        },
                        new
                        {
                            Id = 300,
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "MobileNotification",
                            NameEn = "MobileNotification"
                        },
                        new
                        {
                            Id = 400,
                            CreatedBy = "Admin",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsDeleted = false,
                            NameAr = "WebNotification",
                            NameEn = "WebNotification"
                        });
                });

            modelBuilder.Entity("Framework.Notifications.Entities.NotificationQueue", b =>
                {
                    b.HasOne("Framework.Notifications.Entities.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Framework.Notifications.Entities.NotificationTemplate", b =>
                {
                    b.HasOne("Framework.Notifications.Entities.NotificationType", "NotificationType")
                        .WithMany()
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationType");
                });
#pragma warning restore 612, 618
        }
    }
}
