//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Notifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationTemplatesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationTemplatesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Notifications.NotificationTemplatesRes", typeof(NotificationTemplatesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullName} / Company {CompanyName}
        ///
        ///{Body}.
        /// </summary>
        public static string CompaniesMessageNotification {
            get {
                return ResourceManager.GetString("CompaniesMessageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;&lt;/span&gt;.
        /// </summary>
        public static string CompaniesMessageNotificationAr {
            get {
                return ResourceManager.GetString("CompaniesMessageNotificationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt; Dear {UserFullNameEn}, the authorized person for the company {CompanyName} &lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt; Greetings.  ،
        ///    &lt;p&gt;
        ///Kindly be informed that  the company profile has been suspended due to the  expiration of the commercial registery.
        ///So please make sure that the commercial registery renewed and login to the portal to reactivate the profile again.&lt;/p&gt; 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CRExpiredNotification {
            get {
                return ResourceManager.GetString("CRExpiredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;
        ///&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt;  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt;تحية طيبة،
        /// &lt;p&gt;
        ///يرجى العلم أنه تم  تعليق الملف التعريفي للشركة بسبب   انتهاء صلاحية السجل التجاري.
        ///لذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لإعادة تفعيل ملف الشركة.
        ///&lt;/p&gt; 
        ///            &lt;/h3&gt;&quot;.
        /// </summary>
        public static string CRExpiredNotificationAr {
            get {
                return ResourceManager.GetString("CRExpiredNotificationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///Greetings,
        ///Kindly be informed that  the company profile has been suspended due to the  expiration of the commercial registery.
        ///So please make sure that the commercial registery renewed and login to the portal to reactivate the profile again..
        /// </summary>
        public static string CRExpiredNotificationSMS {
            get {
                return ResourceManager.GetString("CRExpiredNotificationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}
        ///تحية طيبة،
        ///  يرجى العلم أنه تم  تعليق الملف التعريفي للشركة بسبب   انتهاء صلاحية السجل التجاري.
        ///لذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لإعادة تفعيل ملف الشركة&quot;.
        /// </summary>
        public static string CRExpiredNotificationSMSAr {
            get {
                return ResourceManager.GetString("CRExpiredNotificationSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt; Dear {UserFullNameEn}, the authorized person for the company {CompanyName} &lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt; Greetings.  ،
        ///    &lt;p&gt;
        ///Kindly be informed that tomorrow the company profile will be suspended due to the  expiration of the commercial registery.
        ///So please make sure that the commercial registery renewed and login to the portal to update this information.&lt;/p&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CRExpiringNotification {
            get {
                return ResourceManager.GetString("CRExpiringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;
        ///&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt;  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt;تحية طيبة،
        /// &lt;p&gt;
        ///يرجى العلم أنه غدا سيتم تعليق الملف التعريفي للشركة بسبب انتهاء صلاحية السجل التجاري اليوم.
        ///لذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لتحديث هذه المعلومات.
        ///&lt;/p&gt; 
        ///            &lt;/h3&gt;&quot;.
        /// </summary>
        public static string CRExpiringNotificationAr {
            get {
                return ResourceManager.GetString("CRExpiringNotificationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///Greetings,
        ///Kindly be informed that tomorrow the company profile will be suspended due to the  expiration of the commercial registery.
        ///So please make sure that the commercial registery renewed and login to the portal to update this information.&quot;.
        /// </summary>
        public static string CRExpiringNotificationSMS {
            get {
                return ResourceManager.GetString("CRExpiringNotificationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}
        ///تحية طيبة،
        ///يرجى العلم أنه غدا سيتم تعليق الملف التعريفي للشركة بسبب انتهاء صلاحية السجل التجاري اليوم.
        ///لذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لتحديث هذه المعلومات. &quot;.
        /// </summary>
        public static string CRExpiringNotificationSMSAr {
            get {
                return ResourceManager.GetString("CRExpiringNotificationSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot; &gt; Dear {UserFullNameEn}, the authorized person for the company {CompanyName} &lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot; &gt;Greetings،
        ///    &lt;p&gt;Kindly be informed that the company profile will be suspended due to the near expiration of the commercial registery.
        ///So please make sure that the commercial registery renewed and login to the portal to update this information.
        ///&lt;/p&gt; 
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CRPreExpirationNotification {
            get {
                return ResourceManager.GetString("CRPreExpirationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///    &lt;p&gt;يرجى العلم أنه سيتم تعليق الملف التعريفي للشركة بسبب قرب انتهاء صلاحية السجل التجاري.
        ///لذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لتحديث هذه المعلومات.&lt;/p&gt; 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string CRPreExpirationNotificationAr {
            get {
                return ResourceManager.GetString("CRPreExpirationNotificationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///Greetings,
        ///Kindly be informed that the company profile will be suspended due to the near expiration of the commercial registery.
        ///So please make sure that the commercial registery renewed and login to the portal to update this information.&quot;.
        /// </summary>
        public static string CRPreExpirationNotificationSMS {
            get {
                return ResourceManager.GetString("CRPreExpirationNotificationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}
        ///تحية طيبة،
        ///يرجى العلم أنه سيتم تعليق الملف التعريفي للشركة بسبب قرب انتهاء صلاحية السجل التجاري.
        ///لذا يرجى التأكد من تجديد السجل التجاري والدخول إلى البوابة لتحديث هذه المعلومات.
        /// &quot;.
        /// </summary>
        public static string CRPreExpirationNotificationSMSAr {
            get {
                return ResourceManager.GetString("CRPreExpirationNotificationSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نفيدكم بوجود طلبات لديكم تستدعي اتخاذ إجراء .... نأمل اتخاذ اللازم..&lt;/p&gt;.
        /// </summary>
        public static string DelayReminderAr {
            get {
                return ResourceManager.GetString("DelayReminderAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameEn}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Please note that you have late requests، that no action has been taken on yet .... Kindly take the necessary action..&lt;/p&gt;.
        /// </summary>
        public static string DelayReminderEn {
            get {
                return ResourceManager.GetString("DelayReminderEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;Dear {UserFullNameEn} Director of the Department&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;Greetings,
        ///    &lt;p style=&quot;text-align: left;&quot;&gt;Kindly log in to the company registration platform to approve the request to approve the {RequestType} request added to your assignment box via the following link: {InternalUrl}&lt;/p&gt;
        ///&lt;/h3&gt;.
        /// </summary>
        public static string Director_HasNewRequestToReview {
            get {
                return ResourceManager.GetString("Director_HasNewRequestToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال طلب للاعتماد.
        /// </summary>
        public static string Director_HasNewRequestToReview_SubAr {
            get {
                return ResourceManager.GetString("Director_HasNewRequestToReview_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;المكرم {UserFullNameAr} مدير الإدارة&lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///    &lt;p &gt;نأمل منكم التكرم &amp;nbsp;بزيارة منصة تك لاعتماد طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}&lt;/p&gt; 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string Director_HasNewRequestToReviewAr {
            get {
                return ResourceManager.GetString("Director_HasNewRequestToReviewAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn} Director of the Department
        ///
        ///Greetings,
        ///
        ///Kindly log in to Manassa Tech platform to approve the request to approve the {RequestType} request added to your assignment box via the following link: {InternalUrl}.
        /// </summary>
        public static string Director_HasNewRequestToReviewSMS {
            get {
                return ResourceManager.GetString("Director_HasNewRequestToReviewSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكرم {UserFullNameAr} مدير الإدارة
        ///
        ///تحية طيبة،
        ///
        ///نأمل منكم التكرم  بزيارة منصة تك لاعتماد طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}.
        /// </summary>
        public static string Director_HasNewRequestToReviewSMSAr {
            get {
                return ResourceManager.GetString("Director_HasNewRequestToReviewSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request has been submitted for approval.
        /// </summary>
        public static string Director_HasNewRequestToReviewSub {
            get {
                return ResourceManager.GetString("Director_HasNewRequestToReviewSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color: #030062; font-size: 15px; line-height: 25px; text-align: justify; font-weight: bold;&quot;&gt;Dear {NameEn}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align: justify; font-weight: normal;&quot;&gt;Greetings,&lt;/h3&gt;
        ///&lt;p style=&quot;text-align: left;&quot;&gt;Kindly use the following code to activate your email {Code} so you can keep procced&lt;/p&gt;.
        /// </summary>
        public static string EmailCodeVerification {
            get {
                return ResourceManager.GetString("EmailCodeVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color: #030062; font-size: 15px; line-height: 25px; text-align: justify; font-weight: bold;&quot;&gt;المكرم {NameAr} 
        ///&lt;h3 style=&quot;text-align: justify; font-weight: normal;&quot;&gt;تحية طيبة،&lt;/h3&gt;
        ///&lt;p&gt;.الرجاء إستخدام الرمز التالي لتفعيل البريد الإلكتروني {Code} &lt;/p&gt;.
        /// </summary>
        public static string EmailCodeVerificationAr {
            get {
                return ResourceManager.GetString("EmailCodeVerificationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; dir=&quot;rtl&quot;&gt;&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;title style=&quot;dispaly:none&quot;&gt;CST&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body dir=&quot;ltr&quot; style=&quot;padding:0px&quot;&gt;
        ///&lt;div style=&quot;background-color: #030062; text-align: center; padding: 1rem;&quot;&gt;
        ///    &lt;img class=&quot;email_header&quot; style=&quot;max-width: 220px&quot; src=&quot;{RootUrl}/CITC/images/citc_logo_email.png&quot; /&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;0&quot; width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailLayoutTemplate {
            get {
                return ResourceManager.GetString("EmailLayoutTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; dir=&quot;rtl&quot;&gt;&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///    &lt;title style=&quot;dispaly:none&quot;&gt;CST&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body dir=&quot;ltr&quot; style=&quot;padding:0px&quot;&gt;
        ///&lt;div style=&quot;background-color: #030062; text-align: center; padding: 1rem;&quot;&gt;
        ///    &lt;img class=&quot;email_header&quot; style=&quot;max-width: 220px&quot; src=&quot;{RootUrl}/CITC/images/citc_logo_email.png&quot; /&gt;
        ///&lt;/div&gt;
        ///&lt;table border=&quot;0&quot; width=&quot;100%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailLayoutTemplateAr {
            get {
                return ResourceManager.GetString("EmailLayoutTemplateAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;عزيزي {FullName}&lt;/h2&gt;لقد تلقينا طلب تغيير كلمة المرور لحسابك.&lt;br /&gt;لرجاء استخدام هذا الرمز: {Token} لإعادة تعيين
        ///كلمة المرور &lt;br /&gt;يمكنك النقر فوق &lt;a href=&quot;{RootUrl}/{ResetPasswordUrl}&quot;&gt;هنا&lt;/a&gt; لذهاب إلى صفحة إعادة تعيين كلمة المرور
        ///الخاصة بك .&lt;br /&gt;وشكراً&lt;br /&gt;هيئة الاتصالات وتقنية المعلومات  ..
        /// </summary>
        public static string EmailResetPassword {
            get {
                return ResourceManager.GetString("EmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ar&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;G20 Saudi Secretariat&lt;/title&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=0.8, maximum-scale=1.0, user-scalable=no&quot; /&gt;
        ///    &lt;!--[if lt IE 8]&gt;
        ///    &lt;script src=&quot;js/html5.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;js/css3-mediaqueries.js&quot;&gt;&lt;/script&gt;
        ///    &lt;![endif]--&gt;
        ///  
        ///    &lt;style&gt;
        ///        *, *:before, *:after {
        ///            -webkit-box-sizing: border-box;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ErrorPage {
            get {
                return ResourceManager.GetString("ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameEn}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Please note that there are late request with number ({RequestNumber}) that no action has been taken on them yet .... Kindly take the necessary action ..&lt;/p&gt;.
        /// </summary>
        public static string EscalationReminderTemplate {
            get {
                return ResourceManager.GetString("EscalationReminderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealyed Requests.
        /// </summary>
        public static string EscalationReminderTemplate_Sub {
            get {
                return ResourceManager.GetString("EscalationReminderTemplate_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات متأخرة.
        /// </summary>
        public static string EscalationReminderTemplate_SubAr {
            get {
                return ResourceManager.GetString("EscalationReminderTemplate_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameEn}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نفيدكم بوجود طلب متأخر برقم {RequestNumber} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ..&lt;/p&gt;.
        /// </summary>
        public static string EscalationReminderTemplateAr {
            get {
                return ResourceManager.GetString("EscalationReminderTemplateAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///Greetings,
        ///Please note that there are late request with number ({RequestNumber}) that no action has been taken on them yet .... Kindly take the necessary action ...
        /// </summary>
        public static string EscalationReminderTemplateSMS {
            get {
                return ResourceManager.GetString("EscalationReminderTemplateSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيد المكرم {UserFullNameEn}
        ///
        ///تحية طيبة،
        ///
        ///نفيدكم بوجود طلب متأخر برقم {RequestNumber} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ...
        /// </summary>
        public static string EscalationReminderTemplateSMSAr {
            get {
                return ResourceManager.GetString("EscalationReminderTemplateSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameEn}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Please note that there are late request with number ({RequestNumber}) that no action has been taken on them yet .... Kindly take the necessary action ..&lt;/p&gt;.
        /// </summary>
        public static string EscalationTemplate {
            get {
                return ResourceManager.GetString("EscalationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealyed Requests.
        /// </summary>
        public static string EscalationTemplate_Sub {
            get {
                return ResourceManager.GetString("EscalationTemplate_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات متأخرة.
        /// </summary>
        public static string EscalationTemplate_SubAr {
            get {
                return ResourceManager.GetString("EscalationTemplate_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameEn}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نفيدكم بوجود طلب متأخر برقم {RequestNumber} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ..&lt;/p&gt;.
        /// </summary>
        public static string EscalationTemplateAr {
            get {
                return ResourceManager.GetString("EscalationTemplateAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///Greetings,
        ///Please note that there are late request with number ({RequestNumber}) that no action has been taken on them yet .... Kindly take the necessary action ...
        /// </summary>
        public static string EscalationTemplateSMS {
            get {
                return ResourceManager.GetString("EscalationTemplateSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيد المكرم {UserFullNameEn}
        ///
        ///تحية طيبة،
        ///
        ///نفيدكم بوجود طلب متأخر برقم {RequestNumber} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ...
        /// </summary>
        public static string EscalationTemplateSMSAr {
            get {
                return ResourceManager.GetString("EscalationTemplateSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;يسر هيئة الاتصالات وتقنية المعلومات إبلاغكم بالموافقة على {RequestTypeAr} شركتكم {CompanyNameAr} في الهيئة برقم تسجيل {CR} كما يمكنكم تحميل شهادة {RequestTypeAr} عبر الرابط التالي: {ExternalUrl}&lt;/p&gt;
        ///.
        /// </summary>
        public static string FinalApproveToApplicantsAr {
            get {
                return ResourceManager.GetString("FinalApproveToApplicantsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///
        ///Greetings,
        ///
        ///CST is pleased to inform you of the approval to {RequestType} your company {CompanyName} with CST. You can also download the registration certificate via the following link: {ExternalUrl}.
        /// </summary>
        public static string FinalApproveToApplicantsEn {
            get {
                return ResourceManager.GetString("FinalApproveToApplicantsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نأمل منكم التكرم بزيارة منصة تك للاطلاع على الملاحظات الواردة على طلب {RequestTypeAr} الذي تمت مراجعته من قبلكم عبر الرابط التالي: {ExternalUrl}&lt;/p&gt;.
        /// </summary>
        public static string FinalReturnedToApplicantsAr {
            get {
                return ResourceManager.GetString("FinalReturnedToApplicantsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///
        ///Greetings,
        ///
        ///Kindly log in to Manassa Tech platform to preview the notes on your {RequestType} request being reviewed by you via the following link: {ExternalUrl}.
        /// </summary>
        public static string FinalReturnedToApplicantsEn {
            get {
                return ResourceManager.GetString("FinalReturnedToApplicantsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly use the following code to activate your phone number: {Code} .
        /// </summary>
        public static string NumberCodeVerificationSMS {
            get {
                return ResourceManager.GetString("NumberCodeVerificationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نأمل استخدام الرمز التالي لتفعيل رقم الهاتف: {Code}
        ///  .
        /// </summary>
        public static string NumberCodeVerificationSMSAr {
            get {
                return ResourceManager.GetString("NumberCodeVerificationSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt; Dear {UserFullNameEn}, the authorized person for the company {CompanyName} &lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt; Greetings. 
        ///    &lt;p&gt;
        ///Kindly be informed that  the company profile has been suspended due to the  expiration of the registration.
        ///So please login to the portal to apply profile renew request.&lt;/p&gt; 
        ///            &lt;/h3&gt;&quot;.
        /// </summary>
        public static string ProfileExpiredNotification {
            get {
                return ResourceManager.GetString("ProfileExpiredNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;
        ///&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt;  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt;تحية طيبة،
        /// &lt;p&gt;
        ///يرجى العلم أنه تم  تعليق الملف التعريفي للشركة بسبب انتهاء صلاحية التسجيل.
        ///لذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة.
        ///&lt;/p&gt; 
        ///            &lt;/h3&gt;&quot;.
        /// </summary>
        public static string ProfileExpiredNotificationAr {
            get {
                return ResourceManager.GetString("ProfileExpiredNotificationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///Greetings,
        ///Kindly be informed that  the company profile has been suspended due to the  expiration of the registration.
        ///So please login to the portal to apply profile renew request.&quot;.
        /// </summary>
        public static string ProfileExpiredNotificationSMS {
            get {
                return ResourceManager.GetString("ProfileExpiredNotificationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dear {UserFullNameEn}, the authorized person for the company {CompanyNameAr}
        ///Greetings,
        ///Kindly be informed that  the company profile has been suspended due to the  expiration of the registration.
        ///So please login to the portal to apply profile renew request.&quot;.
        /// </summary>
        public static string ProfileExpiredNotificationSMSAr {
            get {
                return ResourceManager.GetString("ProfileExpiredNotificationSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt; Dear {UserFullNameEn}, the authorized person for the company {CompanyName} &lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt; Greetings. 
        ///    &lt;p&gt;
        ///Kindly be informed that tommorrow the company profile will be expired.
        ///So please login to the portal to apply profile renew request.
        ///&lt;/p&gt; 
        ///            &lt;/h3&gt;&quot;.
        /// </summary>
        public static string ProfileExpiringNotification {
            get {
                return ResourceManager.GetString("ProfileExpiringNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;
        ///&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt;  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt;تحية طيبة،
        /// &lt;p&gt;
        ///يرجى العلم أنه باقى يوم على انتهاء صلاحية ملف الشركة .
        ///لذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة.
        ///&lt;/p&gt; 
        ///            &lt;/h3&gt;&quot;.
        /// </summary>
        public static string ProfileExpiringNotificationAr {
            get {
                return ResourceManager.GetString("ProfileExpiringNotificationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///Greetings,
        ///Kindly be informed that tommorrow the company profile will be expired.
        ///So please login to the portal to apply profile renew request.&quot;.
        /// </summary>
        public static string ProfileExpiringNotificationSMS {
            get {
                return ResourceManager.GetString("ProfileExpiringNotificationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}
        ///تحية طيبة،
        ///يرجى العلم أنه باقى يوم على انتهاء صلاحية ملف الشركة .
        ///لذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة. &quot;.
        /// </summary>
        public static string ProfileExpiringNotificationSMSAr {
            get {
                return ResourceManager.GetString("ProfileExpiringNotificationSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt;  Dear {UserFullNameEn}, the authorized person for the company {CompanyName}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt;Greetings,
        /// &lt;p&gt;
        /// Kindly be informed that the company profile will be expired after one month.
        ///So please login to the portal to apply profile renew request
        ///&lt;/p&gt; 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string ProfilePreExpirationNotification {
            get {
                return ResourceManager.GetString("ProfilePreExpirationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;
        ///&lt;h2 style=&quot;&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&quot;&gt;  المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;&quot;text-align:justify;font-weight:normal;&quot;&quot;&gt;تحية طيبة،
        /// &lt;p&gt;
        ///يرجى العلم أنه باقى شهر على انتهاء صلاحية ملف الشركة .
        ///لذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة.
        ///&lt;/p&gt; 
        ///            &lt;/h3&gt;&quot;.
        /// </summary>
        public static string ProfilePreExpirationNotificationAr {
            get {
                return ResourceManager.GetString("ProfilePreExpirationNotificationAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///Greetings,
        ///Kindly be informed that  the company profile will be expired after one month.
        ///So please login to the portal to apply profile renew request.&quot;.
        /// </summary>
        public static string ProfilePreExpirationNotificationSMS {
            get {
                return ResourceManager.GetString("ProfilePreExpirationNotificationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}
        ///تحية طيبة،
        ///يرجى العلم أنه باقى شهر على انتهاء صلاحية ملف الشركة .
        ///لذا يرجى  الدخول إلى البوابة لتقديم طلب تجديد لملف الشركة. 
        /// &quot;.
        /// </summary>
        public static string ProfilePreExpirationNotificationSMSAr {
            get {
                return ResourceManager.GetString("ProfilePreExpirationNotificationSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نفيدكم بوجود طلبات متأخرة للإسناد عند المشرف... نأمل اتخاذ اللازم.&lt;/p&gt;.
        /// </summary>
        public static string RequestAssignedToReviewLateAr {
            get {
                return ResourceManager.GetString("RequestAssignedToReviewLateAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///
        ///Greetings,
        ///
        ///Please note that there are delayed requests for assignment at the administrator ... Kindly take the necessary action..
        /// </summary>
        public static string RequestAssignedToReviewLateEn {
            get {
                return ResourceManager.GetString("RequestAssignedToReviewLateEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نفيدكم بإعادة طلب {RequestTypeAr} الخاص بشركة {CompanyName} عدد {Times} مرات .... نأمل معاينة الطلب، واتخاذ اللازم.&lt;/p&gt;.
        /// </summary>
        public static string ReturnedManyTimesToApplicantsAr {
            get {
                return ResourceManager.GetString("ReturnedManyTimesToApplicantsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameEn}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Please note that the request for the {RequestType} of the company {CompanyName} has been returned for {Times} times .... Kindly preview the request and take the necessary action.&lt;/p&gt;.
        /// </summary>
        public static string ReturnedManyTimesToApplicantsEn {
            get {
                return ResourceManager.GetString("ReturnedManyTimesToApplicantsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نأمل منكم التكرم بزيارة منصة تك الشركات لتعديل الملاحظات الواردة من المشرف على طلب {RequestTypeAr} الذي تمت مراجعته من قبلكم عبر الرابط التالي: {ExternalUrl}&lt;/p&gt;.
        /// </summary>
        public static string ReturnedToReviewerAr {
            get {
                return ResourceManager.GetString("ReturnedToReviewerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameEn}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نفيدكم بوجود طلبات متأخرة لدى المشرف، تستدعي اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم..&lt;/p&gt;.
        /// </summary>
        public static string ReturnedToReviewerDelayAr {
            get {
                return ResourceManager.GetString("ReturnedToReviewerDelayAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameAr}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Please note that there are late requests with the administrator، that no action has been taken on yet .... Kindly take the necessary action..&lt;/p&gt;.
        /// </summary>
        public static string ReturnedToReviewerDelayEn {
            get {
                return ResourceManager.GetString("ReturnedToReviewerDelayEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameEn}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Kindly log in to Manassa Tech platform to amend the notes received from the administrator on your {RequestType} request reviewed by you via the following link: {ExternalUrl}&lt;/p&gt;.
        /// </summary>
        public static string ReturnedToReviewerEn {
            get {
                return ResourceManager.GetString("ReturnedToReviewerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;Dear {UserFullNameEn}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;Greetings,
        ///    &lt;p style=&quot;text-align: left;&quot;&gt;Kindly log in to Manassa Tech platform to study the request to attend a session added to your assignment box via the following link: {InternalUrl}&lt;/p&gt;
        ///&lt;/h3&gt;.
        /// </summary>
        public static string Reviewer_AssignedOnRequestToReview {
            get {
                return ResourceManager.GetString("Reviewer_AssignedOnRequestToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new request to study.
        /// </summary>
        public static string Reviewer_AssignedOnRequestToReview_Sub {
            get {
                return ResourceManager.GetString("Reviewer_AssignedOnRequestToReview_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب جديد للدراسة.
        /// </summary>
        public static string Reviewer_AssignedOnRequestToReview_SubAr {
            get {
                return ResourceManager.GetString("Reviewer_AssignedOnRequestToReview_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;المكرم {UserFullNameAr} المشرف&lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///    &lt;p&gt;نأمل منكم التكرم بزيارة منصة تك  لدراسة طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}&lt;/p&gt; 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string Reviewer_AssignedOnRequestToReviewAr {
            get {
                return ResourceManager.GetString("Reviewer_AssignedOnRequestToReviewAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///
        ///Greetings,
        ///
        ///Kindly log in to Manassa Tech platform to study the request added to your assignment box via the following link: {InternalUrl}.
        /// </summary>
        public static string Reviewer_AssignedOnRequestToReviewSMS {
            get {
                return ResourceManager.GetString("Reviewer_AssignedOnRequestToReviewSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكرم {UserFullNameAr}
        ///
        ///تحية طيبة،
        ///
        ///نأمل منكم التكرم بزيارة منصة تك لدراسة طلب {RequestTypeAr} شركة المضاف لصندوق المهام الخاص بكم عبر الرابط التالي:{InternalUrl}.
        /// </summary>
        public static string Reviewer_AssignedOnRequestToReviewSMSAr {
            get {
                return ResourceManager.GetString("Reviewer_AssignedOnRequestToReviewSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نفيدكم بوجود طلبات متأخرة لدى المراجع {ReviewerName} لم يتم اتخاذ إجراء بشأنها بعد.... نأمل اتخاذ اللازم ..&lt;/p&gt;.
        /// </summary>
        public static string ReviwerDelayAr {
            get {
                return ResourceManager.GetString("ReviwerDelayAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameEn}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Please note that there are late requests with the reviewer {ReviewerName} that no action has been taken on them yet .... Kindly take the necessary action ..&lt;/p&gt;.
        /// </summary>
        public static string ReviwerDelayEn {
            get {
                return ResourceManager.GetString("ReviwerDelayEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تم استلام طلبكم بعد التعديل، وسيتم الرد عليكم فور معالجته ودراسته &amp;nbsp;.&lt;/p&gt;.
        /// </summary>
        public static string SubmitReturnToApplicantsAr {
            get {
                return ResourceManager.GetString("SubmitReturnToApplicantsAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameEn}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Your request has been received after amendment, and it will be studied and we will reply to you soon.&lt;/p&gt;.
        /// </summary>
        public static string SubmitReturnToApplicantsEn {
            get {
                return ResourceManager.GetString("SubmitReturnToApplicantsEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;direction: rtl;&quot;&gt;المكرم {UserFullNameAr}&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;تحية طيبة،&lt;/p&gt;
        ///&lt;p style=&quot;direction: rtl;&quot;&gt;نأمل منكم التكرم بزيارة منصة تك لدراسة طلب {RequestTypeAr} الشركة بعد تعديله. عبر الرابط التالي: {InternalUrl}&lt;/p&gt;.
        /// </summary>
        public static string SubmitReturnToReviewerAr {
            get {
                return ResourceManager.GetString("SubmitReturnToReviewerAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Dear {UserFullNameEn}&lt;/p&gt;
        ///&lt;p&gt;Greetings,&lt;/p&gt;
        ///&lt;p&gt;Kindly log in to Manassa Tech platform to study the company {RequestType} request after it has been amended added to your assignment box via the following link: {InternalUrl}&lt;/p&gt;.
        /// </summary>
        public static string SubmitReturnToReviewerEn {
            get {
                return ResourceManager.GetString("SubmitReturnToReviewerEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;Dear {UserFullNameEn}, the authorized person for the company {CompanyName}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;Greetings,
        ///    &lt;p style=&quot;text-align: left;&quot;&gt;We are pleased to inform you that your {RequestType} request with CST is approved  , You can review your request via the following link: {ExternalUrl}&lt;/p&gt;
        ///&lt;/h3&gt;.
        /// </summary>
        public static string Submitter_RequestApproved {
            get {
                return ResourceManager.GetString("Submitter_RequestApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///    &lt;p&gt;نسعد لإبلاغكم بقبول طلب {RequestTypeAr} في منصة تك بهيئة الاتصالات وتقنية المعلومات. للاطلاع على تفاصيل الطلب والملاحظات:{ExternalUrl}.&lt;/p&gt; 
        /// 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string Submitter_RequestApprovedAr {
            get {
                return ResourceManager.GetString("Submitter_RequestApprovedAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///
        ///Greetings,
        ///
        ///We are please to inform you that your {RequestType} request with CST is approved , You can review your request via the following link: {ExternalUrl}.
        /// </summary>
        public static string Submitter_RequestApprovedSMS {
            get {
                return ResourceManager.GetString("Submitter_RequestApprovedSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}
        ///
        ///تحية طيبة،
        ///
        ///يسعدنا لإبلاغكم بقبول طلب {RequestTypeAr} في منصة تك بهيئة الاتصالات وتقنية المعلومات. للاطلاع على تفاصيل الطلب والملاحظات:{ExternalUrl}.
        ///
        /// .
        /// </summary>
        public static string Submitter_RequestApprovedSMSAr {
            get {
                return ResourceManager.GetString("Submitter_RequestApprovedSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;Dear {UserFullNameEn}, the authorized person for the company {CompanyName}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;Greetings,
        ///    &lt;p style=&quot;text-align: left;&quot;&gt;Kindly log in to Manassa Tech platform to amend the notes received from the reviewers on your registration at CST via the following link: {ExternalUrl}&lt;/p&gt;
        ///&lt;/h3&gt;.
        /// </summary>
        public static string Submitter_RequestNeedsMoreInfo {
            get {
                return ResourceManager.GetString("Submitter_RequestNeedsMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the registration request for some notes..
        /// </summary>
        public static string Submitter_RequestNeedsMoreInfo_Sub {
            get {
                return ResourceManager.GetString("Submitter_RequestNeedsMoreInfo_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة طلب التسجيل.
        /// </summary>
        public static string Submitter_RequestNeedsMoreInfo_SubAr {
            get {
                return ResourceManager.GetString("Submitter_RequestNeedsMoreInfo_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///    &lt;p&gt;نأمل منكم التكرم بزيارة منصة تك لتعديل الملاحظات الواردة على الطلب تسجيلكم في الهيئة عبر الرابط التالي: {ExternalUrl}&lt;/p&gt; 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string Submitter_RequestNeedsMoreInfoAr {
            get {
                return ResourceManager.GetString("Submitter_RequestNeedsMoreInfoAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///
        ///Greetings,
        ///
        ///Kindly log in to Manassa Tech platform to amend the notes received from the reviewers on your {RequestType} at CST via the following link: {ExternalUrl}.
        /// </summary>
        public static string Submitter_RequestNeedsMoreInfoSMS {
            get {
                return ResourceManager.GetString("Submitter_RequestNeedsMoreInfoSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}
        ///
        ///تحية طيبة،
        ///
        ///نأمل منكم التكرم بزيارة منصة تك لتعديل الملاحظات الواردة على الطلب {RequestTypeAr} في الهيئة عبر الرابط التالي: {ExternalUrl}.
        /// </summary>
        public static string Submitter_RequestNeedsMoreInfoSMSAr {
            get {
                return ResourceManager.GetString("Submitter_RequestNeedsMoreInfoSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;Dear {UserFullNameEn}, the authorized person for the company {CompanyName}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;Greetings,
        ///    &lt;p style=&quot;text-align: left;&quot;&gt;We regret to inform you that your {RequestType} request with CST is rejected , for the following reasons : {Reason}, You can review your request via the following link: {ExternalUrl}&lt;/p&gt;
        ///&lt;/h3&gt;.
        /// </summary>
        public static string Submitter_RequestRejected {
            get {
                return ResourceManager.GetString("Submitter_RequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request status.
        /// </summary>
        public static string Submitter_RequestRejected_Sub {
            get {
                return ResourceManager.GetString("Submitter_RequestRejected_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة طلب التسجيل.
        /// </summary>
        public static string Submitter_RequestRejected_SubAr {
            get {
                return ResourceManager.GetString("Submitter_RequestRejected_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}&lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///    &lt;p&gt;نأسف لإبلاغكم برفض طلب {RequestTypeAr} في منصة تك بهيئة الاتصالات وتقنية المعلومات.  تفاصيل الرفض {Reason} وللملاحظات:{ExternalUrl}.&lt;/p&gt; 
        ///
        ///
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string Submitter_RequestRejectedAr {
            get {
                return ResourceManager.GetString("Submitter_RequestRejectedAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}, the authorized person for the company {CompanyName}
        ///
        ///Greetings,
        ///
        ///We regret to inform you that your {RequestType} request with CST is rejected , for the following reasons : {Reason}, You can review your request via the following link: {ExternalUrl}.
        /// </summary>
        public static string Submitter_RequestRejectedSMS {
            get {
                return ResourceManager.GetString("Submitter_RequestRejectedSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكرم {UserFullNameAr} المفوض لشركة {CompanyNameAr}
        ///
        ///تحية طيبة،
        ///
        ///نأسف لإبلاغكم برفض طلب {RequestTypeAr}  في منصة تك بهيئة الاتصالات وتقنية المعلومات.  تفاصيل الرفض {Reason} وللملاحظات:{ExternalUrl}.
        ///.
        /// </summary>
        public static string Submitter_RequestRejectedSMSAr {
            get {
                return ResourceManager.GetString("Submitter_RequestRejectedSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;Dear {UserFullNameEn}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;Greetings,
        ///&lt;p style=&quot;text-align: left;&quot;&gt;Your request has been successfully submitted , and it will be studied and answered within 15 days&lt;/p&gt;
        ///&lt;/h3&gt;.
        /// </summary>
        public static string Submitter_RequestSubmittedSucessfully {
            get {
                return ResourceManager.GetString("Submitter_RequestSubmittedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been submitted.
        /// </summary>
        public static string Submitter_RequestSubmittedSucessfully_Sub {
            get {
                return ResourceManager.GetString("Submitter_RequestSubmittedSucessfully_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال طلبك بنجاح.
        /// </summary>
        public static string Submitter_RequestSubmittedSucessfully_SubAr {
            get {
                return ResourceManager.GetString("Submitter_RequestSubmittedSucessfully_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;المكرم {UserFullNameAr}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///&lt;p&gt;تمت إرسال طلبك بنجاح وستتم دراسته والرد عليكم خلال 15 يومًا من تاريخ تقديم الطلب.&lt;/p&gt; 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string Submitter_RequestSubmittedSucessfullyAr {
            get {
                return ResourceManager.GetString("Submitter_RequestSubmittedSucessfullyAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///
        ///Greetings,
        ///
        ///Your request has been successfully submitted , and it will be studied and answered within 15 days.
        /// </summary>
        public static string Submitter_RequestSubmittedSucessfullySMS {
            get {
                return ResourceManager.GetString("Submitter_RequestSubmittedSucessfullySMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكرم {UserFullNameAr}
        ///
        ///تحية طيبة،
        ///
        ///تمت إرسال طلبك بنجاح وستتم دراسته والرد عليكم خلال 15 يومًا من تاريخ تقديم الطلب..
        /// </summary>
        public static string Submitter_RequestSubmittedSucessfullySMSAr {
            get {
                return ResourceManager.GetString("Submitter_RequestSubmittedSucessfullySMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;Dear {UserFullNameEn}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;Greetings,
        ///&lt;p style=&quot;text-align: left;&quot;&gt;Kindly log in to Manassa Tech platform to study the request to attend a session added to your assignment box via the following link: {InternalUrl}&lt;/p&gt;&lt;h3&gt;.
        /// </summary>
        public static string Supervisor_RequestSubmittedWaitingForReview {
            get {
                return ResourceManager.GetString("Supervisor_RequestSubmittedWaitingForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request has been submitted for review.
        /// </summary>
        public static string Supervisor_RequestSubmittedWaitingForReview_Sub {
            get {
                return ResourceManager.GetString("Supervisor_RequestSubmittedWaitingForReview_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال طلب للمراجعة.
        /// </summary>
        public static string Supervisor_RequestSubmittedWaitingForReview_SubAr {
            get {
                return ResourceManager.GetString("Supervisor_RequestSubmittedWaitingForReview_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;المكرم {UserFullNameAr} المشرف&lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///    &lt;p&gt;نأمل منكم التكرم بزيارة منصة تك لدراسة طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}&lt;/p&gt; 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string Supervisor_RequestSubmittedWaitingForReviewAr {
            get {
                return ResourceManager.GetString("Supervisor_RequestSubmittedWaitingForReviewAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///
        ///Greetings,
        ///
        ///Kindly log in to Manassa Tech platform to study the request to attend a session added to your assignment box via the following link: {InternalUrl}.
        /// </summary>
        public static string Supervisor_RequestSubmittedWaitingForReviewSMS {
            get {
                return ResourceManager.GetString("Supervisor_RequestSubmittedWaitingForReviewSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكرم {UserFullNameAr} المشرف 
        ///
        ///تحية طيبة،
        ///
        ///نأمل منكم التكرم بزيارة منصة تك لدراسة طلب {RequestTypeAr} المضاف لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}.
        /// </summary>
        public static string Supervisor_RequestSubmittedWaitingForReviewSMSAr {
            get {
                return ResourceManager.GetString("Supervisor_RequestSubmittedWaitingForReviewSMSAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;Dear {UserFullNameEn}&lt;/h2&gt;
        ///&lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;Greetings,
        ///    &lt;p style=&quot;text-align: left;&quot;&gt;Kindly log in to the company registration platform to study the request to examine financial information added to your assignment box via the following link: {InternalUrl}
        ///    &lt;/p&gt;
        ///&lt;/h3&gt;.
        /// </summary>
        public static string Supervisor_ReviewerApprovedTheRequest {
            get {
                return ResourceManager.GetString("Supervisor_ReviewerApprovedTheRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request has been submitted for review.
        /// </summary>
        public static string Supervisor_ReviewerApprovedTheRequest_Sub {
            get {
                return ResourceManager.GetString("Supervisor_ReviewerApprovedTheRequest_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال طلب للمراجعة.
        /// </summary>
        public static string Supervisor_ReviewerApprovedTheRequest_SubAr {
            get {
                return ResourceManager.GetString("Supervisor_ReviewerApprovedTheRequest_SubAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;color:#030062; font-size:15px; line-height:25px; text-align:justify;font-weight:bold;&quot;&gt;المكرم {UserFullNameAr} المشرف&lt;/h2&gt;
        ///            &lt;h3 style=&quot;text-align:justify;font-weight:normal;&quot;&gt;تحية طيبة،
        ///    &lt;p&gt;نأمل منكم التكرم بزيارة منصة تك لدراسة المعلومات المالية المضافة لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}&lt;/p&gt; 
        ///            &lt;/h3&gt;.
        /// </summary>
        public static string Supervisor_ReviewerApprovedTheRequestAr {
            get {
                return ResourceManager.GetString("Supervisor_ReviewerApprovedTheRequestAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {UserFullNameEn}
        ///
        ///Greetings,
        ///
        ///Kindly log in to the company registration platform to study the request to examine financial information added to your assignment box via the following link: {InternalUrl}.
        /// </summary>
        public static string Supervisor_ReviewerApprovedTheRequestSMS {
            get {
                return ResourceManager.GetString("Supervisor_ReviewerApprovedTheRequestSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكرم {UserFullNameAr} المشرف
        ///
        ///تحية طيبة،
        ///
        ///نأمل منكم التكرم بزيارة منصة تك لدراسة المعلومات المالية المضافة لصندوق المهام الخاص بكم عبر الرابط التالي: {InternalUrl}.
        /// </summary>
        public static string Supervisor_ReviewerApprovedTheRequestSMSAr {
            get {
                return ResourceManager.GetString("Supervisor_ReviewerApprovedTheRequestSMSAr", resourceCulture);
            }
        }
    }
}
