//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Notifications.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Notifications.Resources.NotificationsResources", typeof(NotificationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bcc.
        /// </summary>
        public static string Bcc {
            get {
                return ResourceManager.GetString("Bcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc.
        /// </summary>
        public static string Cc {
            get {
                return ResourceManager.GetString("Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Method.
        /// </summary>
        public static string DeliveryMethod {
            get {
                return ResourceManager.GetString("DeliveryMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Address.
        /// </summary>
        public static string EmailFromAddress {
            get {
                return ResourceManager.GetString("EmailFromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Name.
        /// </summary>
        public static string EmailFromName {
            get {
                return ResourceManager.GetString("EmailFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Address.
        /// </summary>
        public static string EmailToAddress {
            get {
                return ResourceManager.GetString("EmailToAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by email from address.
        /// </summary>
        public static string Filter_by_email_from_address {
            get {
                return ResourceManager.GetString("Filter_by_email_from_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by email from name.
        /// </summary>
        public static string Filter_by_email_from_name {
            get {
                return ResourceManager.GetString("Filter_by_email_from_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by email to address.
        /// </summary>
        public static string Filter_by_email_to_address {
            get {
                return ResourceManager.GetString("Filter_by_email_to_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by subject.
        /// </summary>
        public static string Filter_by_subject {
            get {
                return ResourceManager.GetString("Filter_by_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Send Date.
        /// </summary>
        public static string LastSendDate {
            get {
                return ResourceManager.GetString("LastSendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Date After.
        /// </summary>
        public static string LastSendDateAfter {
            get {
                return ResourceManager.GetString("LastSendDateAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Date Before.
        /// </summary>
        public static string LastSendDateBefore {
            get {
                return ResourceManager.GetString("LastSendDateBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Body.
        /// </summary>
        public static string MailBody {
            get {
                return ResourceManager.GetString("MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail From.
        /// </summary>
        public static string MailFrom {
            get {
                return ResourceManager.GetString("MailFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailIs Body Html.
        /// </summary>
        public static string MailIsBodyHtml {
            get {
                return ResourceManager.GetString("MailIsBodyHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data To Display..
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Email Details List.
        /// </summary>
        public static string NotificationEmailDetails_Title {
            get {
                return ResourceManager.GetString("NotificationEmailDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend message seccessfully.
        /// </summary>
        public static string Notifications_data_Message {
            get {
                return ResourceManager.GetString("Notifications_data_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seccessfully.
        /// </summary>
        public static string Notifications_data_title {
            get {
                return ResourceManager.GetString("Notifications_data_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReSend.
        /// </summary>
        public static string ReSend {
            get {
                return ResourceManager.GetString("ReSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string SendErrorMessage {
            get {
                return ResourceManager.GetString("SendErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SendStatusCode {
            get {
                return ResourceManager.GetString("SendStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Enable SSL.
        /// </summary>
        public static string SmtpEnableSSL {
            get {
                return ResourceManager.GetString("SmtpEnableSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Port.
        /// </summary>
        public static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default Credentials.
        /// </summary>
        public static string UseDefaultCredentials {
            get {
                return ResourceManager.GetString("UseDefaultCredentials", resourceCulture);
            }
        }
    }
}
